config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :comments
  resources :posts
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get 'admin_page', to: 'pages#admin_page'

  # Defines the root path route ("/")
  root "posts#index"
  resources :posts do
  resources :comments, only: [:create, :destroy]
   end

   resources :users do
    member do
      post 'add_role'
      delete 'remove_role'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
#  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, :dependent => :destroy
  belongs_to :user
  validates :name, presence: true
  validates :title, presence: true, length: { minimum: 5 }
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  validates :name, presence: true, uniqueness: true

  belongs_to :resource,
             :polymorphic => true,
             :optional => true


  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify

end

app/models/user.rb
class User < ApplicationRecord
  rolify :before_add => :before_add_method

  def before_add_method(role)
    # do something before it gets added
  end

  after_create :assign_default_role

  def assign_default_role
    self.add_role(:newuser) if self.roles.blank?
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy

  def admin?
    has_role?(:admin)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = 'Bu sayfayı görmeye yetkili değilsiniz'
    redirect_to(request.referer || root_path)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_post, only: [:create, :destroy]
  before_action :find_comment, only: [:destroy]

  def create
    @comment = @post.comments.new(comment_params)
    if @comment.save
      redirect_to post_path(@post), notice: 'Yorum başarıyla oluşturuldu.'
    else
      redirect_to post_path(@post), alert: 'Yorum oluşturulurken bir hata oluştu.'
    end
  end

  def destroy
    @comment.destroy
    redirect_to post_path(@post), notice: 'Yorum başarıyla silindi.'
  end

  private

  def find_post
    @post = Post.find(params[:post_id])
  end

  def find_comment
    @comment = @post.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body, :commenter)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /posts or /posts.json
  def index
    @posts = policy_scope(Post)
  end

  # GET /posts/1 or /posts/1.json
  def show
    authorize @post
  end

   # GET /posts/new
   def new
    @post = current_user.posts.build
    authorize @post
  end

  # GET /posts/1/edit
  def edit
    authorize @post
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.build(post_params)
    authorize @post

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post başarılı bir şekilde oluşturuldu." }
        format.json { render :show, stat  us: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    authorize @post
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post başarılı bir şekilde güncellendi." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    authorize @post
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post başarılı bir şekilde kaldırıldı." }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:name, :title, :body, :user_id)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :add_role, :remove_role]

  def add_role
    @user.add_role params[:role]
    redirect_to @user, notice: "Role #{params[:role]} added to user."
  end

  def remove_role
    @user.remove_role params[:role]
    redirect_to @user, notice: "Role #{params[:role]} removed from user."
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
  <p>
    <b>Yorum Yapan:</b>
    <%= comment.commenter %>
  </p>

  <p>
    <b>Yorum:</b>
    <%= comment.body %>
  </p>
  <% if current_user.present? %>
  <p>
    <%= link_to 'Yorumu sil', [comment.post, comment], method: :delete,
     data: { 'turbo-confirm': 'Bu yorumu silmek istediğinize emin misiniz?', 'turbo-method': :delete }, class: 'btn btn-danger' %>
  <% end %>
  </p>
</div>

app/views/comments/_form.html.erb
<% if current_user.present? %>
  <%= form_for([@post, @post.comments.build]) do |f| %>
    <div class="field">
      <%= f.label :commenter, "Yorum Yapan" %><br />
      <%= f.text_field :commenter %>
    </div>
    <div class="field">
      <%= f.label :body, "Yorum" %><br />
      <%= f.text_area :body %>
    </div>
    <div class="actions">
      <%= f.submit "Yorum Ekle", class: 'btn btn-primary' %>
    </div>
  <% end %>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div id="flash-messages">
      <% flash.each do |type, message| %>
        <div class="alert alert-<%= type %>">
          <%= message %>
        </div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "hata") %> bu gönderinin kaydedilmesini engelledi:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, "Başlık", style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :title, "Yazar", style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, "İçerik", style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit "Yeni gönderiyi oluştur" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Başlık:</strong>
    <%= post.name %>
  </p>

  <p>
    <strong>Yazar:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>İçerik:</strong>
    <%= post.body %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Gönderiyi düzenle</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Gönderiyi göster", @post %> |
  <%= link_to "Gönderilere geri dön", posts_path %>
</div>

app/views/posts/index.html.erb
<h1>Gönderileri listele</h1>
<table>
  <tr>
    <th>Başlık</th>
    <th>Yazar</th>
    <th>İçerik</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.name %></td>
    <td><%= post.title %></td>
    <td><%= post.body %></td>
    <td><%= link_to 'Göster', post %></td>
   <% if current_user.present? %> 
    <td><%= link_to 'Düzenle', edit_post_path(post) %></td>
    <td><%= link_to 'Sil', post_path(post), method: :delete,
     data: { 'turbo-confirm': 'Bu yazıyı silmek istediğinize emin misiniz?', 'turbo-method': :delete } %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />
<% if current_user.present? %>
<%= link_to 'Yeni gönderi', new_post_path %>
<% end %>
<br/>

<% if user_signed_in? %> 
 <div> Hoşgeldiniz <%= current_user.email %> </div> 
  <%= button_to "Sign out", destroy_user_session_path, method: :delete %> 
<% else %>
  <%= button_to "Sign in", new_user_session_path %> 
<% end %>

app/views/posts/new.html.erb
<h1>Yeni Gönderi</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Gönderilere Geri Dön", posts_path %>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Başlık:</b>
  <%= @post.title %>
</p>

<p>
  <b>Yazar:</b>
  <%= @post.name %>
</p>

<p>
  <b>İçerik:</b>
  <%= @post.body %>
</p>
<hr>
<h2>Yorumlar</h2>
<%= render @post.comments %>


<%= render "comments/form" %>

<br />

<% if current_user.present? %>
<%= link_to 'Gönderiyi Düzenle', edit_post_path(@post) %> |
<% end %>

<%= link_to 'Gönderilere Geri Dön', posts_path %>